version: '3'

services:
  web:
    container_name: myriad-dashboard
    image: myriadsocial/myriad-dashboard
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3002:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.4
        aliases:
          - myriad-dashboard

networks:
  myriad:
    external: true
