export const LOADING = 'LOADING'
export type LOADING_TYPE = typeof LOADING

export const ERROR = 'ERROR'
export type ERROR_TYPE = typeof ERROR

export const FETCH_ALL_REPORTED_POST = 'FETCH_ALL_REPORTED_POST'
export type FETCH_ALL_REPORTED_POST_TYPE = typeof FETCH_ALL_REPORTED_POST

export const FETCH_ALL_REPORTED_USER = 'FETCH_ALL_REPORTED_USER'
export type FETCH_ALL_REPORTED_USER_TYPE = typeof FETCH_ALL_REPORTED_USER

export const UPDATE_ALL_REPORTED_POST = 'UPDATE_ALL_REPORTED_POST'
export type UPDATE_ALL_REPORTED_POST_TYPE = typeof UPDATE_ALL_REPORTED_POST

export const UPDATE_ALL_REPORTED_USER = 'UPDATE_ALL_REPORTED_USER'
export type UPDATE_ALL_REPORTED_USER_TYPE = typeof UPDATE_ALL_REPORTED_USER
